version: "3.8"

services:
  django:
    container_name: django
    build:
      context: ./django
      args:
        DOMAIN:
    environment:
      DJANGO_SETTINGS_MODULE: "ftt.settings"
      DJANGO_ALLOW_ASYNC_UNSAFE: "true"
    #   DJANGO_DEBUG: "False"
    env_file: .env
    ports:
      - "443:443"
    networks:
      - my-network
    # volumes:
      # - ./django:/ftt
    # depends_on:
      # - db
    # restart: unless-stopped

  # db:
  #   image: postgres:latest
  #   env_file: .env.prod
  #   container_name: db-container
  #   ports:
  #     - "5433:5432"
  #   networks:
  #     - my-network
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   restart: unless-stopped


# volumes:
#   backend_static:
#   db-data:
#   media_volume:
#   nginx_log:

networks:
  my-network:
    driver: bridge